import { COURSE_SCHEDULE,courseName } from './mockData'
import { countdown,getCurrentOrNext } from './schedule'
import type { AIProvider,AISettings,ChatMessage,Material,ReferenceItem,SmartAction,Task,UserSettings } from '../types'

type Context={tasks:Task[];materials:Material[];references:ReferenceItem[];profile:UserSettings}
const cleanBase=(x:string)=>x.replace(/\/+$/,'')
async function request(provider:AIProvider,messages:ChatMessage[],settings:AISettings,context:Context){const local=provider==='local',endpoint=local?settings.localEndpoint:settings.cloudEndpoint,key=local?settings.localKey:settings.cloudKey,model=local?settings.localModel:settings.cloudModel;if(!endpoint)throw new Error(`Endpoint ${local?'lokal':'cloud'} belum diatur.`);if(!key)throw new Error(`API key ${local?'lokal':'cloud'} belum diatur.`);const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),settings.timeoutMs);const next=getCurrentOrNext(COURSE_SCHEDULE),active=context.tasks.filter(t=>!t.completed).sort((a,b)=>a.dueAt.localeCompare(b.dueAt));const system=`Anda adalah Copilot KelasKu. Jawab ringkas dalam Bahasa Indonesia. Profil: ${context.profile.program}, semester ${context.profile.semester}, kelas ${context.profile.className}. Waktu kini ${new Date().toLocaleString('id-ID')}. Kuliah berikutnya ${next.course.name}, ${next.start.toLocaleString('id-ID')} (${countdown(next.remaining)}). Tugas aktif: ${active.map(t=>`${t.title} (${courseName(t.courseCode)}, ${t.dueAt})`).join('; ')||'tidak ada'}. Jangan mengarang data. Untuk aksi, tambahkan tepat satu baris terakhir bila relevan: [ACTION:NAVIGATE:Tugas], [ACTION:SEARCH:Materi:kata], atau [ACTION:ADD_TASK:judul|ISO deadline opsional|kode mata kuliah opsional].`;try{const response=await fetch(`${cleanBase(endpoint)}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:'system',content:system},...messages.map(({role,content})=>({role,content}))],temperature:.3}),signal:controller.signal});if(!response.ok)throw new Error(`${response.status} ${await response.text().then(x=>x.slice(0,180))}`);const json=await response.json() as {choices?:{message?:{content?:string}}[]};const content=json.choices?.[0]?.message?.content;if(!content)throw new Error('Respons AI kosong.');return content}finally{window.clearTimeout(timer)}}
export async function chat(messages:ChatMessage[],settings:AISettings,context:Context){try{return{content:await request(settings.provider,messages,settings,context),provider:settings.provider}}catch(first){if(settings.provider==='local'&&settings.cloudKey){return{content:await request('cloud',messages,settings,context),provider:'cloud' as const,fallback:true}}throw first}}
export function parseSmartAction(text:string):{text:string;action:SmartAction}{const match=text.match(/\[ACTION:(NAVIGATE|SEARCH|ADD_TASK):([^\]]+)\]\s*$/i);if(!match)return{text,action:{type:'none'}};const body=match[2],clean=text.replace(match[0],'').trim();if(match[1].toUpperCase()==='NAVIGATE'){const page=body as SmartAction extends {type:'navigate';page:infer P}?P:never;return{text:clean,action:{type:'navigate',page}}}if(match[1].toUpperCase()==='SEARCH'){const[page,...q]=body.split(':');if(page==='Materi'||page==='Referensi')return{text:clean,action:{type:'search',page,query:q.join(':')}}}const[title,dueAt,courseCode]=body.split('|');return{text:clean,action:{type:'add-task',title:title.trim(),dueAt:dueAt?.trim()||undefined,courseCode:courseCode?.trim()||undefined}}}
