import { COURSE_SCHEDULE,courseName } from './mockData'
import { countdown,getCurrentOrNext } from './schedule'
import { validDate } from './storage'
import type { AIProvider,AISettings,ChatMessage,Material,Page,ReferenceItem,SmartAction,Task,UserSettings } from '../types'
type Context={tasks:Task[];materials:Material[];references:ReferenceItem[];profile:UserSettings}
const cleanBase=(x:unknown)=>typeof x==='string'?x.replace(/\/+$/,''):''
const contentOf=(json:unknown)=>{if(typeof json!=='object'||json===null)return null;const choices=(json as {choices?:unknown}).choices;if(!Array.isArray(choices))return null;const message=(choices[0] as {message?:unknown}|undefined)?.message;const content=typeof message==='object'&&message!==null?(message as {content?:unknown}).content:null;return typeof content==='string'&&content.trim()?content:null}
async function request(provider:AIProvider,messages:ChatMessage[],settings:AISettings,context:Context){const server=provider==='server',endpoint=server?'/api':cleanBase(settings.localEndpoint),key=server?'':settings.localKey,model=server?settings.serverModel:settings.localModel;if(!endpoint)throw new Error('Endpoint lokal belum diatur.');if(!server&&!key)throw new Error('API key lokal belum diatur.');const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),settings.timeoutMs);const next=getCurrentOrNext(COURSE_SCHEDULE),active=context.tasks.filter(t=>!t.completed&&validDate(t.dueAt)).sort((a,b)=>Date.parse(a.dueAt)-Date.parse(b.dueAt));const system=`Anda adalah Copilot KelasKu. Jawab ringkas dalam Bahasa Indonesia. Profil: ${context.profile.program}, semester ${context.profile.semester}, kelas ${context.profile.className}. Waktu kini ${new Date().toLocaleString('id-ID')}. Kuliah berikutnya ${next.course.name}, ${next.start.toLocaleString('id-ID')} (${countdown(next.remaining)}). Tugas aktif: ${active.map(t=>`${t.title} (${courseName(t.courseCode)}, ${t.dueAt})`).join('; ')||'tidak ada'}. Jangan mengarang data. Aksi opsional hanya satu baris terakhir: [ACTION:NAVIGATE:Tugas], [ACTION:SEARCH:Materi:kata], atau [ACTION:ADD_TASK:judul|ISO deadline|kode mata kuliah].`;try{const response=await fetch(`${endpoint}/chat/completions`,{method:'POST',headers:server?{'Content-Type':'application/json'}:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:'system',content:system},...messages.filter(m=>typeof m.content==='string').map(({role,content})=>({role,content}))],temperature:.3}),signal:controller.signal});if(!response.ok){const raw=await response.text().then(x=>x.slice(0,300));let detail=raw;try{const parsed=JSON.parse(raw);if(parsed&&typeof parsed.error==='string')detail=parsed.error}catch{/* biarkan teks apa adanya */}throw new Error(`${response.status} ${detail}`)}const content=contentOf(await response.json());if(!content)throw new Error('Format respons provider AI tidak valid atau kosong.');return content}finally{window.clearTimeout(timer)}}
export async function chat(messages:ChatMessage[],settings:AISettings,context:Context){try{return{content:await request(settings.provider,messages,settings,context),provider:settings.provider}}catch(first){if(settings.provider==='local')return{content:await request('server',messages,settings,context),provider:'server' as const,fallback:true};throw first}}
const pages:Page[]=['Beranda','Jadwal','Tugas','Materi','Referensi','Kalender','Pengaturan']
export function parseSmartAction(value:unknown):{text:string;action:SmartAction}{const text=typeof value==='string'?value:'';const match=text.match(/\[ACTION:(NAVIGATE|SEARCH|ADD_TASK):([^\]\r\n]{1,500})\]\s*$/i);if(!match)return{text,action:{type:'none'}};const clean=text.slice(0,match.index).trim(),kind=match[1].toUpperCase(),body=match[2].trim();if(kind==='NAVIGATE'){const page=pages.find(p=>p.toLowerCase()===body.toLowerCase());return page?{text:clean,action:{type:'navigate',page}}:{text,action:{type:'none'}}}if(kind==='SEARCH'){const split=body.indexOf(':');if(split<1)return{text,action:{type:'none'}};const page=body.slice(0,split),query=body.slice(split+1).trim();return (page==='Materi'||page==='Referensi')&&query?{text:clean,action:{type:'search',page,query}}:{text,action:{type:'none'}}}const [rawTitle,rawDue,rawCourse,...extra]=body.split('|');const title=rawTitle?.trim(),dueAt=rawDue?.trim(),courseCode=rawCourse?.trim();if(!title||extra.length||title.length>160||(dueAt&&!validDate(dueAt))||(courseCode&&!COURSE_SCHEDULE.some(c=>c.code===courseCode)))return{text,action:{type:'none'}};return{text:clean,action:{type:'add-task',title,dueAt:dueAt||undefined,courseCode:courseCode||undefined}}}
