import type { Material } from "../types";

export const INITIAL_MATERIALS: Material[] = [
  {
    id: "mat-mateko-pertemuan-02",
    title: "Catatan Kuliah & Pembahasan Lengkap: Permintaan, Penawaran & Keseimbangan Pasar",
    courseCode: "KP21517007",
    meetingNo: 2,
    type: "Catatan",
    description:
      "Rangkuman komprehensif 20 slide PPT dosen (Ibu Vepi Apiati). Dilengkapi narasi contoh nyata sehari-hari, grafik kurva di buku berpetak, serta pembahasan step-by-step latihan soal slide 16–20 pada kertas bergaris binder.",
    url: "/materi/KP21517007/pertemuan-02/index.html",
    createdAt: "2026-08-20T12:00:00.000Z",
  },
  {
    id: "mat-mateko-pertemuan-03",
    title: "Catatan Kuliah: Pengaruh Pajak, Subsidi, & Keseimbangan Multi-Pasar (2 Komoditas)",
    courseCode: "KP21517007",
    meetingNo: 3,
    type: "Catatan",
    description:
      "Catatan komprehensif kuliah Matematika Ekonomi Pertemuan 03: Pengaruh Pajak spesifik (t), Pajak proporsional (r), dan Subsidi spesifik (s) terhadap pergeseran kurva, insidensi beban konsumen/produsen, total kas pemerintah, serta metode 4 langkah eliminasi SPLDV pada pasar 2 komoditas.",
    url: "/materi/KP21517007/pertemuan-03/index.html",
    createdAt: "2026-08-27T17:00:00.000Z",
  },
  {
    id: "mat-mateko-pertemuan-04",
    title: "Catatan Kuliah: Fungsi Biaya, Penerimaan, dan Laba",
    courseCode: "KP21517007",
    meetingNo: 4,
    type: "Catatan",
    description:
      "Catatan komprehensif kuliah Matematika Ekonomi Pertemuan 04: Fungsi Biaya (biaya tetap, variabel, total, rata-rata, marginal), Fungsi Penerimaan (total, rata-rata, marginal), Laba, dan Titik Impas (BEP). Dilengkapi contoh soal dan latihan.",
    url: "/materi/KP21517007/pertemuan-04/index.html",
    createdAt: "2026-09-03T02:00:00.000Z",
  },
  {
    id: "mat-mateko-pertemuan-05",
    title: "Catatan Kuliah: Penerapan Fungsi Non-Linear dalam Ekonomi",
    courseCode: "KP21517007",
    meetingNo: 5,
    type: "Catatan",
    description:
      "Catatan komprehensif kuliah Matematika Ekonomi Pertemuan 05: Fungsi Permintaan & Penawaran Kuadrat, Keseimbangan Pasar Non-Linear, Pengaruh Pajak Spesifik (t) & Subsidi (s), dan Kurva Transformasi Produksi (PPF) dengan pembahasan bertahap.",
    url: "/materi/KP21517007/pertemuan-05/index.html",
    createdAt: "2026-09-10T02:30:00.000Z",
  },
  {
    id: "tool-kalkulator-mateko",
    title: "Aplikasi Bantuan: Kalkulator Matematika Ekonomi Lengkap",
    courseCode: "KP21517007",
    meetingNo: 4,
    type: "Dokumen",
    description:
      "Kalkulator interaktif untuk pasar, pajak, subsidi, dua komoditas, fungsi biaya, BEP, laba/rugi, fungsi konsumsi, dan tabungan. Angka dapat diubah bebas dan hasil disertai langkah perhitungan.",
    url: "/tools/kalkulator-mateko/index.html",
    createdAt: "2026-09-03T05:00:00.000Z",
  },
  {
    id: "mat-analisis-kompleks-pertemuan-03",
    title: "Catatan Kuliah: Pengantar Sistem Bilangan Kompleks & Operasi Aljabar",
    courseCode: "KP21517003",
    meetingNo: 3,
    type: "Catatan",
    description:
      "Catatan komprehensif kuliah Analisis Kompleks bersama Ibu Vepi Apiati, S.Pd., M.Pd. Mencakup definisi bilangan kompleks z = a + bi, hierarki sistem bilangan, operasi aljabar (penjumlahan, pengurangan, perkalian, pembagian), serta sifat-sifat sekawan (konjugat) dilengkapi foto arsip tulisan tangan asli.",
    url: "/materi/KP21517003/pertemuan-03/index.html",
    createdAt: "2026-08-24T08:30:00.000Z",
  },
  {
    id: "tool-kalkulator-analisis-kompleks",
    title: "Aplikasi Bantuan: Kalkulator Bilangan Kompleks Edukatif (Step-by-Step & Bidang Argand)",
    courseCode: "KP21517003",
    meetingNo: 3,
    type: "Dokumen",
    description:
      "Aplikasi kalkulator interaktif khusus mahasiswa Pendidikan Matematika. Menjabarkan setiap langkah aljabar formal (penjumlahan, pengurangan, perkalian distributif, pembagian sekawan penyebut, modulus, konjugat, polar & Euler) lengkap dengan visualisasi bidang Argand 2D.",
    url: "/tools/kalkulator-kompleks/index.html",
    createdAt: "2026-08-24T09:25:00.000Z",
  },
  {
    id: "tool-kalkulator-integral-kompleks",
    title: "Aplikasi Bantuan: Kalkulator Integral Kontur & Teorema Residu Cauchy",
    courseCode: "KP21517003",
    meetingNo: 9,
    type: "Dokumen",
    description:
      "Alat bantu eksplorasi integral lintasan kurva tertutup pada bidang kompleks. Menentukan letak titik singular (di dalam / luar kurva), Teorema Cauchy-Goursat, Rumus Integral Cauchy, dan Teorema Residu Cauchy dengan bidang Argand interaktif.",
    url: "/tools/kalkulator-integral-kompleks/index.html",
    createdAt: "2026-08-24T10:05:00.000Z",
  },
  {
    id: "mat-analisis-kompleks-pertemuan-04",
    title: "Catatan Kuliah: Sifat Operasi Dasar, Bilangan Sekawan & Nilai Mutlak",
    courseCode: "KP21517003",
    meetingNo: 4,
    type: "Catatan",
    description:
      "Catatan kuliah Pertemuan 04 (31 Agustus 2026) hasil pencatatan langsung di kelas. Mencakup 6 sifat operasi dasar pada bilangan kompleks (ketertutupan sampai invers), bilangan sekawan beserta hasil kali/jumlah/selisihnya dengan z, penurunan rumus Re z dan Im z, pembuktian konjugat ganda, nilai mutlak |z|, serta pembahasan dua soal papan tulis dengan pola pangkat i. Dilengkapi 3 lembar catatan tulis tangan asli dan 2 foto papan tulis.",
    url: "/materi/KP21517003/pertemuan-04/index.html",
    createdAt: "2026-08-31T02:30:00.000Z",
  },
  {
    id: "mat-analisis-kompleks-pertemuan-05",
    title: "Catatan Kuliah: Perkalian Titik, Silang, Geometri Vektor & Bentuk Polar",
    courseCode: "KP21517003",
    meetingNo: 5,
    type: "Catatan",
    description:
      "Catatan resmi perkuliahan Analisis Kompleks bersama Ibu Vepi Apiati, S.Pd., M.Pd. Mencakup perkalian titik (dot product), perkalian silang (cross product), geometri vektor pada bidang Argand (aturan jajar genjang dan jarak euclides), persamaan lingkaran kompleks, bentuk kutub (polar), rumus Euler, serta alur 4 tahap penentuan argumen dengan arsip 7 lembar catatan tulis tangan asli.",
    url: "/materi/KP21517003/pertemuan-05/index.html",
    createdAt: "2026-09-07T06:30:00.000Z",
  },
  {
    id: "mat-analisis-kompleks-pertemuan-06",
    title: "Bahan Baca: Rumus De Moivre, Pemangkatan & Penarikan Akar Kompleks",
    courseCode: "KP21517003",
    meetingNo: 6,
    type: "Catatan",
    description:
      "Bahan baca mandiri persiapan perkuliahan lanjutan dari bentuk polar. Mencakup aturan perkalian dan pembagian sudut polar, rumus De Moivre untuk pemangkatan zⁿ beserta bukti induksi, dan penarikan n akar kompleks yang membentuk segi-n beraturan di bidang Argand.",
    url: "/materi/KP21517003/pertemuan-06/index.html",
    createdAt: "2026-09-07T07:00:00.000Z",
  },
  {
    id: "tool-kalkulator-polar-demoivre",
    title: "Aplikasi Bantuan: Kalkulator Polar, De Moivre & Akar Kompleks",
    courseCode: "KP21517003",
    meetingNo: 5,
    type: "Dokumen",
    description:
      "Kalkulator lengkap langkah demi langkah untuk materi Analisis Kompleks: konversi ke bentuk polar & Euler dengan alur 4 tahap dosen, pecahan pi eksak, bentuk akar modulus, perkalian titik & silang, grafik jajar genjang, jarak 2 titik, pemangkatan De Moivre, dan pencarian n akar kompleks.",
    url: "/tools/kalkulator-polar-demoivre/index.html",
    createdAt: "2026-08-31T00:35:00.000Z",
  },
  {
    id: "mat-analisis-real-pertemuan-02",
    title: "Catatan Kuliah: Landasan Teori Himpunan & Pembuktian Teorema De Morgan",
    courseCode: "KP21517004",
    meetingNo: 2,
    type: "Catatan",
    description:
      "Catatan komprehensif kuliah Analisis Real bersama Ibu Linda Herawati, S.Pd., M.Pd. Mencakup notasi kuantor formal, operasi himpunan (irisan, gabungan, selisih), himpunan kosong ({ } vs {∅}), dan pembuktian formal Teorema 1.1.4 De Morgan dilengkapi Diagram Venn interaktif.",
    url: "/materi/KP21517004/pertemuan-02/index.html",
    createdAt: "2026-08-24T15:30:00.000Z",
  },
  {
    id: "mat-analisis-real-pertemuan-03",
    title: "Catatan Kuliah: Teorema 1.1.4 Bartle, Inklusi Ganda & Pembuktian Aljabar Himpunan",
    courseCode: "KP21517004",
    meetingNo: 3,
    type: "Catatan",
    description:
      "Catatan resmi kuliah Analisis Real Pertemuan 03: Bedah Teorema 1.1.4 (a) & (b) De Morgan buku Bartle menggunakan metode Double Inclusion (Inklusi Ganda), rantai ekuivalensi notasi pembentuk himpunan (:=), manipulasi A \\ A = ∅, dan galeri lembar catatan tulis tangan asli SiDU Campus.",
    url: "/materi/KP21517004/pertemuan-03/index.html",
    createdAt: "2026-08-27T08:00:00.000Z",
  },
  {
    id: "mat-analisis-real-pertemuan-04",
    title: "Catatan Kuliah: Sifat Terurut Baik dan Prinsip Induksi Matematika",
    courseCode: "KP21517004",
    meetingNo: 4,
    type: "Catatan",
    description: "Materi aktual kuliah 3 September 2026 berdasarkan Bartle 1.2.1–1.2.2: Sifat Terurut Baik, pernyataan dan pembuktian Prinsip Induksi Matematika, kesalahan umum, serta pembuktian rinci Latihan 4.",
    url: "/materi/KP21517004/pertemuan-04/index.html",
    createdAt: "2026-09-03T01:00:00.000Z",
  },
  {
    id: "mat-analisis-real-pertemuan-05",
    title: "Catatan Kuliah: Latihan Induksi 1.2 & Sifat Aljabar di ℝ",
    courseCode: "KP21517004",
    meetingNo: 5,
    type: "Catatan",
    description: "Pembahasan Latihan Section 1.2 No 1–11, pengantar sembilan aksioma lapangan (A1–A4, M1–M4, D), dan Teorema 2.1.2 Kelompok 1.",
    url: "/materi/KP21517004/pertemuan-05/index.html",
    createdAt: "2026-09-11T16:00:00.000Z",
  },
  {
    id: "mat-analisis-real-pertemuan-06",
    title: "Catatan Kuliah: Sifat Aljabar di ℝ (Bartle 2.1), Bedah Kelompok 2 & Pembahasan Latihan 1–6",
    courseCode: "KP21517004",
    meetingNo: 6,
    type: "Catatan",
    description: "Catatan kuliah resmi Kamis, 24 September 2026: Presentasi Kelompok 2 (Teorema 2.1.3), analisis koreksi/komentar Bu Linda, serta pembahasan lengkap Latihan Section 2.1 No. 1–6.",
    url: "/materi/KP21517004/pertemuan-06/index.html",
    createdAt: "2026-09-24T08:45:00.000Z",
  },
  {
    id: "mat-analisis-real-tugas-section-2-1",
    title: "Tugas Mandiri: Pembahasan Lengkap Latihan Section 2.1 (Bartle Hal 31 No 1–6)",
    courseCode: "KP21517004",
    meetingNo: 6,
    type: "Dokumen",
    description: "Dokumen PDF resmi penyelesaian latihan Section 2.1 (No 1–6 dan khusus No 2a–2b) dengan penulisan aksiomatis rapi dan rumus matematika formal.",
    url: "/tugas/KP21517004/232151098_Ryan_Wardiana_Analisis_Real_Latihan_Section_2.1_Bartle.pdf",
    createdAt: "2026-09-24T08:50:00.000Z",
  },
  {
    id: "tool-panduan-induksi",
    title: "Alat Bantu: Panduan Interaktif Pembuktian Induksi",
    courseCode: "KP21517004",
    meetingNo: 4,
    type: "Dokumen",
    description: "Checklist struktur bukti, perbandingan tiga jenis induksi, serta pemeriksa jembatan Latihan 4. Pemeriksaan angka membantu memahami pola tanpa menggantikan bukti formal.",
    url: "/tools/panduan-induksi/index.html",
    createdAt: "2026-09-03T01:20:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-01",
    title: "Bahan Belajar Pertemuan 01 — Deret Taylor dan Analisis Galat (Penjelasan Ibu Linda)",
    courseCode: "KP21517001",
    meetingNo: 1,
    type: "Catatan",
    description: "Materi terstruktur Pertemuan 01 Metode Numerik: angka bena, deret Taylor dan Maclaurin, galat pemotongan dan pembulatan oleh Ibu Linda Herawati.",
    url: "/materi/KP21517001/pertemuan-01/index.html",
    createdAt: "2026-09-02T01:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-02",
    title: "Bahan Belajar Pertemuan 02 — Solusi Nirlanjar dengan Metode Tertutup (Kelompok 1)",
    courseCode: "KP21517001",
    meetingNo: 2,
    type: "Catatan",
    description: "Materi terstruktur Pertemuan 02 Metode Numerik: Teorema Bolzano pengurung akar f(a)f(b) < 0, metode bagi dua (biseksi), dan regula falsi klasik oleh Kelompok 1.",
    url: "/materi/KP21517001/pertemuan-02/index.html",
    createdAt: "2026-09-02T02:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-03",
    title: "Bahan Belajar Pertemuan 03 — Solusi Nirlanjar: Regula Falsi Perbaikan & Metode Terbuka (Kelompok 2 - Masih Abu-Abu)",
    courseCode: "KP21517001",
    meetingNo: 3,
    type: "Catatan",
    description: "Modul terpadu materi gabungan perkuliahan offline Kelompok 2: Regula Falsi Perbaikan (Skema Illinois), lelaran titik tetap, Newton-Raphson, dan metode secant beserta contoh soal riil.",
    url: "/materi/KP21517001/pertemuan-03/index.html",
    createdAt: "2026-09-02T03:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-04",
    title: "Bahan Belajar Pertemuan 04 — Solusi Sistem Persamaan Nirlanjar (Harapan Materi - Kelompok 3)",
    courseCode: "KP21517001",
    meetingNo: 4,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: sistem persamaan nirlanjar (SPNL multivariabel), metode Newton multivariabel, dan matriks Jacobian oleh Kelompok 3.",
    url: "/materi/KP21517001/pertemuan-04/index.html",
    createdAt: "2026-09-02T04:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-05",
    title: "Bahan Belajar Pertemuan 05 — Sistem Persamaan Lanjar: Eliminasi Gauss Modifikasi & Dekomposisi LU Doolittle (Materi Pengantar)",
    courseCode: "KP21517001",
    meetingNo: 5,
    type: "Catatan",
    description: "Materi pengantar silabus resmi Bu Linda Bab 4: SPL eliminasi Gauss modifikasi (partial pivoting), dekomposisi LU Gauss / Doolittle, dan substitusi dua tahap.",
    url: "/materi/KP21517001/pertemuan-05/index.html",
    createdAt: "2026-09-02T05:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-06",
    title: "Bahan Belajar Pertemuan 06 — Dekomposisi LU Reduksi Crout & Metode Cholesky (Kelompok 4 - Ryan, Najla, Nabila)",
    courseCode: "KP21517001",
    meetingNo: 6,
    type: "Catatan",
    description: "Materi presentasi utama Kelompok 4 (Ryan Wardiana, Najla Salsabila, Nabila Azzahra): faktorisasi matriks dekomposisi LU reduksi Crout (u_ii = 1) dan dekomposisi Cholesky (A = L L^T) untuk matriks simetris definit positif.",
    url: "/materi/KP21517001/pertemuan-06/index.html",
    createdAt: "2026-09-02T06:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-07",
    title: "Bahan Belajar Pertemuan 07 — Interpolasi Polinom dan Lagrange (Harapan Materi - Kelompok 6)",
    courseCode: "KP21517001",
    meetingNo: 7,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: konsep interpolasi kurva, interpolasi linier, kuadratik, dan polinomial Lagrange derajat n.",
    url: "/materi/KP21517001/pertemuan-07/index.html",
    createdAt: "2026-09-02T07:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-08",
    title: "Bahan Belajar Pertemuan 08 — Interpolasi Newton dan Newton-Gregory (Harapan Materi - Kelompok 7)",
    courseCode: "KP21517001",
    meetingNo: 8,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: tabel selisih terbagi Newton serta interpolasi selisih maju dan mundur Newton-Gregory.",
    url: "/materi/KP21517001/pertemuan-08/index.html",
    createdAt: "2026-09-02T08:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-09",
    title: "Bahan Belajar Pertemuan 09 — Integrasi Numerik Metode Pias (Harapan Materi - Kelompok 8)",
    courseCode: "KP21517001",
    meetingNo: 9,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: integrasi numerik pendekatan pias (kaidah segi empat, kaidah trapesium, dan kaidah titik tengah).",
    url: "/materi/KP21517001/pertemuan-09/index.html",
    createdAt: "2026-09-02T09:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-10",
    title: "Bahan Belajar Pertemuan 10 — Integrasi Numerik Metode Newton-Cotes (Harapan Materi - Kelompok 9)",
    courseCode: "KP21517001",
    meetingNo: 10,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: aturan Simpson 1/3, Simpson 3/8, dan kaidah integrasi Newton-Cotes komposit.",
    url: "/materi/KP21517001/pertemuan-10/index.html",
    createdAt: "2026-09-02T10:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-11",
    title: "Bahan Belajar Pertemuan 11 — Integrasi Romberg dan Kuadratur Gauss (Harapan Materi)",
    courseCode: "KP21517001",
    meetingNo: 11,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: ekstrapolasi Richardson, integrasi Romberg, dan kuadratur Gauss-Legendre bobot optimal.",
    url: "/materi/KP21517001/pertemuan-11/index.html",
    createdAt: "2026-09-02T11:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-12",
    title: "Bahan Belajar Pertemuan 12 — Diferensiasi Numerik Beda Hingga (Harapan Materi)",
    courseCode: "KP21517001",
    meetingNo: 12,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: diferensiasi numerik selisih maju, mundur, pusat, serta turunan kedua dengan deret Taylor.",
    url: "/materi/KP21517001/pertemuan-12/index.html",
    createdAt: "2026-09-02T12:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-13",
    title: "Bahan Belajar Pertemuan 13 — Solusi PDB: Metode Euler dan Heun (Harapan Materi)",
    courseCode: "KP21517001",
    meetingNo: 13,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: masalah nilai awal PDB orde satu dengan metode Euler dan metode Euler modifikasi (Heun).",
    url: "/materi/KP21517001/pertemuan-13/index.html",
    createdAt: "2026-09-02T13:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-14",
    title: "Bahan Belajar Pertemuan 14 — Solusi PDB: Runge-Kutta Orde 4 (Harapan Materi)",
    courseCode: "KP21517001",
    meetingNo: 14,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: metode Runge-Kutta orde 4 (RK4) untuk PDB tunggal dan sistem persamaan diferensial.",
    url: "/materi/KP21517001/pertemuan-14/index.html",
    createdAt: "2026-09-02T14:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-15",
    title: "Bahan Belajar Pertemuan 15 — Penerapan Kasus Nyata & Studi Pemodelan Matematika (Harapan Materi)",
    courseCode: "KP21517001",
    meetingNo: 15,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: studi kasus pemodelan matematika sains/rekayasa dan optimasi numerik terapan.",
    url: "/materi/KP21517001/pertemuan-15/index.html",
    createdAt: "2026-09-02T15:00:00.000Z",
  },
  {
    id: "mat-metnum-pertemuan-16",
    title: "Bahan Belajar Pertemuan 16 — Evaluasi Akhir Semester & Sintesis Komprehensif (Harapan Materi)",
    courseCode: "KP21517001",
    meetingNo: 16,
    type: "Catatan",
    description: "Materi perkiraan silabus resmi Bu Linda: evaluasi terpadu seluruh metode komputasi numerik dan persiapan UAS.",
    url: "/materi/KP21517001/pertemuan-16/index.html",
    createdAt: "2026-09-02T16:00:00.000Z",
  },
  {
    id: "tool-lab-metode-numerik",
    title: "Laboratorium Metode Numerik Lengkap: Langkah, Tabel & Grafik",
    courseCode: "KP21517001",
    meetingNo: 1,
    type: "Dokumen",
    description: "Tujuh kelompok kalkulator dalam satu tempat: galat dan Taylor, akar persamaan, SPL, interpolasi dan regresi, turunan, integrasi, serta PDB. Semua menampilkan langkah, tabel, dan grafik yang mudah dibaca.",
    url: "/tools/lab-metode-numerik/index.html",
    createdAt: "2026-09-02T17:00:00.000Z",
  },
];


