import type { Course,SyllabusMeeting } from '../types'
export const COURSE_SCHEDULE: Course[] = [
{id:1,code:'KP21517003',name:'Analisis Kompleks',sks:2,dayIndex:1,dayName:'Senin',startTime:'07:00',endTime:'08:40',room:'C.1.3',lecturer:'Vepi Apiati, S.Pd., M.Pd.',color:'#6558df',topics:['Bilangan Kompleks','Fungsi Analitik','Persamaan Cauchy-Riemann','Integral Kontur']},
{id:2,code:'KP21517006',name:'Seminar Pendidikan Matematika',sks:3,dayIndex:1,dayName:'Senin',startTime:'09:35',endTime:'12:05',room:'MAT-1',lecturer:'Dr. Nani Ratnaningsih, M.Pd.',color:'#ee9250',topics:['Kajian Artikel Jurnal','Proposal Penelitian','Metodologi Pendidikan Matematika','Presentasi Seminar']},
{id:3,code:'KP21517001',name:'Metode Numerik',sks:3,dayIndex:3,dayName:'Rabu',startTime:'15:05',endTime:'17:35',room:'K.D.2.4',lecturer:'Linda Herawati, S.Pd., M.Pd.',color:'#279b72',topics:['Analisis Galat','Pencarian Akar','Sistem Persamaan Linier','Integrasi Numerik']},
{id:4,code:'KP21517004',name:'Analisis Real',sks:2,dayIndex:4,dayName:'Kamis',startTime:'07:00',endTime:'08:40',room:'K.D.2.4',lecturer:'Linda Herawati, S.Pd., M.Pd.',color:'#db5874',topics:['Kelengkapan Real','Topologi Bilangan Real','Barisan dan Limit','Integral Riemann']},
{id:5,code:'KP21517007',name:'Matematika Ekonomi',sks:3,dayIndex:4,dayName:'Kamis',startTime:'09:35',endTime:'12:05',room:'C.3.1',lecturer:'Vepi Apiati, S.Pd., M.Pd.',color:'#438bd2',topics:['Permintaan dan Penawaran','Keseimbangan Pasar','Optimasi','Input-Output']},
{id:6,code:'KF21518001',name:'Skripsi',sks:6,dayIndex:0,dayName:'Minggu',startTime:'06:00',endTime:'16:00',room:'FKIP / Sekolah Mitra',lecturer:'Satya Santika, S.Pd., M.Pd.',color:'#9564bf',topics:['Proposal','Pengumpulan Data','Analisis Data','Sidang dan Publikasi']}
]
const regular=(titles:string[],practical:number[]=[]):SyllabusMeeting[]=>titles.map((title,i)=>({meeting:i+1,title,kind:i===7?'UTS':i===15?'UAS':practical.includes(i+1)?'Praktikum':'Teori',summary:i===7?'Evaluasi materi pertemuan 1–7.':i===15?'Evaluasi akhir dan integrasi capaian semester.':`Mempelajari ${title.toLowerCase()} secara konseptual dan terapan.`,activity:i===7||i===15?'Evaluasi pembelajaran.':practical.includes(i+1)?'Latihan komputasi, analisis hasil, dan dokumentasi.':'Diskusi konsep, contoh, dan latihan terarah.'}))
export const SYLLABUS:Record<string,SyllabusMeeting[]>={
KP21517003:regular(['Sistem Bilangan Kompleks','Geometri Bilangan Kompleks','Fungsi Variabel Kompleks','Limit dan Kekontinuan','Turunan Kompleks dan Fungsi Analitik','Persamaan Cauchy–Riemann','Transformasi Elementer','UTS','Integral Garis Kompleks','Teorema Integral Cauchy','Rumus Integral Cauchy','Deret Taylor Kompleks','Titik Singular','Teorema Residu dan Aplikasi','Deret Laurent','UAS']),
KP21517006:regular(['Identifikasi Masalah Pendidikan Matematika','Perumusan Masalah dan Tujuan','Penelusuran Literatur Ilmiah','Telaah Kritis Artikel','Kerangka Teoretis','Metodologi Penelitian','Penyusunan Kajian Pustaka','UTS: Draft Proposal','Teknik Presentasi Ilmiah','Seminar Proposal I','Seminar Proposal II','Peer Review Proposal','Revisi Berbasis Masukan','Etika dan Sitasi Ilmiah','Finalisasi Artikel Seminar','UAS: Final Paper']),
KP21517001:regular(['Pengantar dan Sumber Galat','Aritmetika Komputer dan Propagasi Galat','Metode Biseksi','Metode Regula Falsi','Metode Newton–Raphson','Sistem Persamaan Linier: Eliminasi Gauss','Dekomposisi dan Iterasi SPL','UTS','Interpolasi Lagrange','Interpolasi Newton','Diferensiasi Numerik','Integrasi Trapesium','Integrasi Simpson','Penyelesaian Numerik PDB','Praktikum Proyek Komputasi','UAS: Proyek Komputasi'],[3,4,5,6,7,9,10,11,12,13,14,15]),
KP21517004:regular(['Aksioma Lapangan Bilangan Real','Aksioma Kelengkapan dan Supremum','Topologi pada Bilangan Real','Barisan Bilangan Real','Konvergensi dan Kriteria Cauchy','Limit Barisan dengan Epsilon','Deret Bilangan Real','UTS','Limit Fungsi','Kekontinuan Fungsi','Kekontinuan Seragam','Turunan dan Teorema Nilai Rata-rata','Barisan Fungsi','Integral Riemann','Teorema Dasar Kalkulus','UAS']),
KP21517007:regular(['Model dan Fungsi Ekonomi','Fungsi Linier Permintaan','Fungsi Linier Penawaran','Keseimbangan Pasar','Pajak dan Subsidi','Elastisitas','Fungsi Konsumsi dan Tabungan','UTS','Turunan dalam Analisis Marginal','Fungsi Biaya dan Penerimaan','Optimasi Laba','Optimasi Berkendala','Integral dalam Ekonomi','Matriks dan Sistem Ekonomi','Model Input–Output Leontief','UAS']),
KF21518001:['Pengajuan Judul','Proposal BAB 1–3','Seminar Proposal','Validasi Instrumen dan Data Lapangan','Olah Data dan BAB 4–5','Sidang Munaqasyah','Publikasi Ilmiah'].map((title,i)=>({meeting:i+1,title,kind:'Tahap Riset',summary:`Tahap ${i+1} pelaksanaan riset skripsi: ${title}.`,activity:'Catat progres, bukti kerja, hasil bimbingan, dan tindak lanjut.'}))
}
export const courseName=(code:string)=>COURSE_SCHEDULE.find(c=>c.code===code)?.name??'Umum'
