import type { AIProvider, Material, MeetingNote, ReferenceCategory, ReferenceItem, Task, UserSettings } from "../types";
export type DeletedKind = "tasks" | "materials" | "references" | "meeting_notes";
// Kunci API TIDAK BOLEH punya nilai bawaan dari import.meta.env: apa pun yang
// diawali VITE_ ikut dipanggang ke dalam bundel JavaScript dan bisa dibaca
// siapa pun yang membuka aplikasi. Provider "server" memakai proxy
// /api/chat/completions, kuncinya hanya ada di env server Vercel.
export const DEFAULT_SETTINGS: UserSettings = { name:"", nim:"", email:"", program:"Pendidikan Matematika", semester:"7", className:"C", target:"", notifications:false, sound:false, theme:"light", ai:{ provider:"server", localEndpoint:import.meta.env.VITE_NINEROUTER_BASE_URL||"http://127.0.0.1:20128/v1", localKey:"", localModel:import.meta.env.VITE_NINEROUTER_MODEL||"cx/gpt-5.6-sol", cloudEndpoint:import.meta.env.VITE_OPENAI_BASE_URL||"https://api.openai.com/v1", cloudKey:"", cloudModel:import.meta.env.VITE_OPENAI_MODEL||"gpt-4o-mini", timeoutMs:60000 } };
const providers: AIProvider[] = ["server","local","cloud"];
const object=(x:unknown):x is Record<string,unknown>=>typeof x==="object"&&x!==null;
const text=(x:unknown,f="")=>typeof x==="string"?x:f;
const meeting=(x:unknown)=>typeof x==="number"&&Number.isInteger(x)&&x>=1&&x<=16?x:undefined;
export const validDate=(x:unknown):x is string=>typeof x==="string"&&x.trim()!==""&&!Number.isNaN(Date.parse(x));
const iso=(x:unknown,f:string)=>validDate(x)?new Date(x).toISOString():f;
export const normalizeTask=(x:unknown):Task|null=>{if(!object(x)||!text(x.id)||!text(x.title)||!validDate(x.dueAt))return null;const n=new Date().toISOString();return{id:text(x.id),title:text(x.title),courseCode:text(x.courseCode,"UMUM"),meetingNo:meeting(x.meetingNo),description:text(x.description),dueAt:iso(x.dueAt,n),completed:x.completed===true,createdAt:iso(x.createdAt,n),updatedAt:validDate(x.updatedAt)?iso(x.updatedAt,n):undefined}};
export const normalizeMaterial=(x:unknown):Material|null=>{if(!object(x)||!text(x.id)||!text(x.title))return null;const n=new Date().toISOString(),types=["Catatan","Dokumen","Slide","Video"] as const;return{id:text(x.id),title:text(x.title),courseCode:text(x.courseCode,"UMUM"),meetingNo:meeting(x.meetingNo),type:types.includes(x.type as Material["type"])?x.type as Material["type"]:"Catatan",description:text(x.description),url:text(x.url),createdAt:iso(x.createdAt,n),updatedAt:validDate(x.updatedAt)?iso(x.updatedAt,n):undefined}};
const categories:ReferenceCategory[]=["Jurnal","E-Book","Website","Drive/File","Video","Catatan"];
export const normalizeReference=(x:unknown):ReferenceItem|null=>{if(!object(x)||!text(x.id)||!text(x.title))return null;const n=new Date().toISOString();return{id:text(x.id),title:text(x.title),courseCode:text(x.courseCode,"UMUM"),meetingNo:meeting(x.meetingNo),category:categories.includes(x.category as ReferenceCategory)?x.category as ReferenceCategory:"Catatan",urlOrPath:text(x.urlOrPath),description:text(x.description),tags:Array.isArray(x.tags)?x.tags.filter((v):v is string=>typeof v==="string"):[],createdAt:iso(x.createdAt,n),updatedAt:validDate(x.updatedAt)?iso(x.updatedAt,n):undefined}};
export const normalizeMeetingNote=(x:unknown):MeetingNote|null=>{if(!object(x)||!text(x.id)||!text(x.courseCode)||!meeting(x.meetingNo))return null;return{id:text(x.id),courseCode:text(x.courseCode),meetingNo:meeting(x.meetingNo)!,content:text(x.content),updatedAt:iso(x.updatedAt,new Date().toISOString())}};
export const normalizeSettings=(x:unknown):UserSettings=>{const v=object(x)?x:{},a=object(v.ai)?v.ai:{};return{name:text(v.name),nim:text(v.nim),email:text(v.email),program:text(v.program,DEFAULT_SETTINGS.program),semester:text(v.semester,DEFAULT_SETTINGS.semester),className:text(v.className,DEFAULT_SETTINGS.className),target:text(v.target),notifications:v.notifications===true,sound:v.sound===true,theme:v.theme==="dark"?"dark":"light",ai:{provider:providers.includes(a.provider as AIProvider)?a.provider as AIProvider:DEFAULT_SETTINGS.ai.provider,localEndpoint:text(a.localEndpoint,DEFAULT_SETTINGS.ai.localEndpoint),localKey:text(a.localKey),localModel:text(a.localModel,DEFAULT_SETTINGS.ai.localModel),cloudEndpoint:text(a.cloudEndpoint,DEFAULT_SETTINGS.ai.cloudEndpoint),cloudKey:text(a.cloudKey),cloudModel:text(a.cloudModel,DEFAULT_SETTINGS.ai.cloudModel),timeoutMs:typeof a.timeoutMs==="number"&&a.timeoutMs>=1000&&a.timeoutMs<=120000?a.timeoutMs:DEFAULT_SETTINGS.ai.timeoutMs}}};
