import type { BackupData,Material,ReferenceCategory,ReferenceItem,Task,Theme,UserSettings } from '../types'
const K={tasks:'kelasku_tasks',materials:'kelasku_materials',references:'kelasku_references',settings:'kelasku_settings',theme:'kelasku_theme'} as const
export const DEFAULT_SETTINGS:UserSettings={name:'',nim:'',email:'',program:'Pendidikan Matematika',semester:'7',className:'C',target:'',notifications:false,sound:false,theme:'light',ai:{provider:'local',localEndpoint:import.meta.env.VITE_NINEROUTER_BASE_URL||'http://127.0.0.1:20128/v1',localKey:import.meta.env.VITE_NINEROUTER_API_KEY||'',localModel:import.meta.env.VITE_NINEROUTER_MODEL||'cx/gpt-5.6-sol',cloudEndpoint:import.meta.env.VITE_OPENAI_BASE_URL||'https://api.openai.com/v1',cloudKey:import.meta.env.VITE_OPENAI_API_KEY||'',cloudModel:import.meta.env.VITE_OPENAI_MODEL||'gpt-4o-mini',timeoutMs:20000}}
const object=(x:unknown):x is Record<string,unknown>=>typeof x==='object'&&x!==null
const text=(x:unknown,fallback='')=>typeof x==='string'?x:fallback
export const validDate=(x:unknown):x is string=>typeof x==='string'&&x.trim()!==''&&!Number.isNaN(Date.parse(x))
const iso=(x:unknown,fallback:string)=>validDate(x)?new Date(x).toISOString():fallback
const read=(key:string):unknown=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):undefined}catch{return undefined}}
const save=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{/* storage unavailable */}}
export const normalizeTask=(x:unknown):Task|null=>{if(!object(x)||!text(x.id)||!text(x.title)||!validDate(x.dueAt))return null;const now=new Date().toISOString();return{id:text(x.id),title:text(x.title),courseCode:text(x.courseCode,'UMUM'),description:text(x.description),dueAt:iso(x.dueAt,now),completed:x.completed===true,createdAt:iso(x.createdAt,now),updatedAt:validDate(x.updatedAt)?iso(x.updatedAt,now):undefined}}
export const normalizeMaterial=(x:unknown):Material|null=>{if(!object(x)||!text(x.id)||!text(x.title))return null;const types=['Catatan','Dokumen','Slide','Video'] as const,now=new Date().toISOString();return{id:text(x.id),title:text(x.title),courseCode:text(x.courseCode,'UMUM'),type:types.includes(x.type as typeof types[number])?x.type as Material['type']:'Catatan',description:text(x.description),url:text(x.url),createdAt:iso(x.createdAt,now),updatedAt:validDate(x.updatedAt)?iso(x.updatedAt,now):undefined}}
const categories:ReferenceCategory[]=['Jurnal','E-Book','Website','Drive/File','Video','Catatan']
export const normalizeReference=(x:unknown):ReferenceItem|null=>{if(!object(x)||!text(x.id)||!text(x.title))return null;const now=new Date().toISOString();return{id:text(x.id),title:text(x.title),courseCode:text(x.courseCode,'UMUM'),category:categories.includes(x.category as ReferenceCategory)?x.category as ReferenceCategory:'Catatan',urlOrPath:text(x.urlOrPath),description:text(x.description),tags:Array.isArray(x.tags)?x.tags.filter((v):v is string=>typeof v==='string'):[],createdAt:iso(x.createdAt,now),updatedAt:validDate(x.updatedAt)?iso(x.updatedAt,now):undefined}}
const list=<T>(x:unknown,normalize:(v:unknown)=>T|null):T[]=>Array.isArray(x)?x.map(normalize).filter((v):v is T=>v!==null):[]
export const normalizeSettings=(x:unknown):UserSettings=>{const v=object(x)?x:{},rawAi=object(v.ai)?v.ai:{};return{name:text(v.name),nim:text(v.nim),email:text(v.email),program:text(v.program,DEFAULT_SETTINGS.program),semester:text(v.semester,DEFAULT_SETTINGS.semester),className:text(v.className,DEFAULT_SETTINGS.className),target:text(v.target),notifications:v.notifications===true,sound:v.sound===true,theme:v.theme==='dark'?'dark':'light',ai:{provider:rawAi.provider==='cloud'?'cloud':'local',localEndpoint:text(rawAi.localEndpoint,DEFAULT_SETTINGS.ai.localEndpoint),localKey:text(rawAi.localKey),localModel:text(rawAi.localModel,DEFAULT_SETTINGS.ai.localModel),cloudEndpoint:text(rawAi.cloudEndpoint,DEFAULT_SETTINGS.ai.cloudEndpoint),cloudKey:text(rawAi.cloudKey),cloudModel:text(rawAi.cloudModel,DEFAULT_SETTINGS.ai.cloudModel),timeoutMs:typeof rawAi.timeoutMs==='number'&&rawAi.timeoutMs>=1000&&rawAi.timeoutMs<=120000?rawAi.timeoutMs:DEFAULT_SETTINGS.ai.timeoutMs}}}
export const getTasks=()=>list(read(K.tasks),normalizeTask);export const saveTasks=(v:Task[])=>save(K.tasks,list(v,normalizeTask))
export const getMaterials=()=>list(read(K.materials),normalizeMaterial);export const saveMaterials=(v:Material[])=>save(K.materials,list(v,normalizeMaterial))
export const getReferences=()=>list(read(K.references),normalizeReference);export const saveReferences=(v:ReferenceItem[])=>save(K.references,list(v,normalizeReference))
export const getSettings=()=>normalizeSettings(read(K.settings));export const saveSettings=(v:UserSettings)=>{const safe=normalizeSettings(v);save(K.settings,safe);try{localStorage.setItem(K.theme,safe.theme)}catch{/* storage unavailable */}}
export const getTheme=():Theme=>{try{return localStorage.getItem(K.theme)==='dark'?'dark':'light'}catch{return'light'}}
export function exportDataAsJSON(){const settings=getSettings();settings.ai={...settings.ai,localKey:'',cloudKey:''};const data:BackupData={version:3,exportedAt:new Date().toISOString(),tasks:getTasks(),materials:getMaterials(),references:getReferences(),settings};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`kelasku-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
export function importDataFromJSON(raw:string){const d:unknown=JSON.parse(raw);if(!object(d)||!Array.isArray(d.tasks)||!Array.isArray(d.materials)||!Array.isArray(d.references)||!object(d.settings))throw new Error('Format cadangan tidak valid');saveTasks(list(d.tasks,normalizeTask));saveMaterials(list(d.materials,normalizeMaterial));saveReferences(list(d.references,normalizeReference));const imported=normalizeSettings(d.settings),current=getSettings();imported.ai.localKey=current.ai.localKey;imported.ai.cloudKey=current.ai.cloudKey;saveSettings(imported)}
export function resetStorage(){Object.values(K).forEach(k=>{try{localStorage.removeItem(k)}catch{/* storage unavailable */}})}
